version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: "12345"
    ports:
      - "3306:3306"
